### ISSUE TITLE
/bin/bash: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by razvan-panda** [input-output-hk/stack2nix#74] opened 2017-11-03 12:45 UTC
How to reproduce, git clone https://github.com/haskell/haskell-ide-engine and run `stack2nix . > default.nix`:

```
[neo@nixos:~/Sources/haskell-ide-engine]$ stack2nix . > default.nix
Ensuring cabal2nix version is >= 2.2.1 ...
Ensuring git version is >= 2 ...
Ensuring cabal version is >= 1 ...
Running /tmp/s2n/programs/x86_64-linux/ghc-8.0.2.temp/ghc-8.0.2/configure --prefix=/tmp/s2n/programs/x86_64-linux/ghc-8.0.2/ in directory /tmp/s2n/programs/x86_64-linux/ghc-8.0.2.temp/ghc-8.0.2/ exited with ExitFailure 1

checking for path to top of build tree... 
/tmp/s2n/programs/x86_64-linux/ghc-8.0.2.temp/ghc-8.0.2/configure: utils/ghc-pwd/dist-install/build/tmp/ghc-pwd-bindist: /bin/bash: bad interpreter: No such file or directory
configure: error: cannot determine current directory


Error: Error encountered while configuring GHC with
         /tmp/s2n/programs/x86_64-linux/ghc-8.0.2.temp/ghc-8.0.2/configure --prefix=/tmp/s2n/programs/x86_64-linux/ghc-8.0.2/
         run in /tmp/s2n/programs/x86_64-linux/ghc-8.0.2.temp/ghc-8.0.2/

The following directories may now contain files, but won't be used by stack:
  - /tmp/s2n/programs/x86_64-linux/ghc-8.0.2.temp/
  - /tmp/s2n/programs/x86_64-linux/ghc-8.0.2/
```

**Comment by domenkozar** [comment] 2017-11-08 19:49
This means that it's not using `--nix` when calling stack.

**Comment by domenkozar** [comment] 2017-11-08 19:49
cc @jmitchell

**Comment by domenkozar** [comment] 2017-11-08 19:49
Ref: https://github.com/commercialhaskell/stack/issues/2634

**Comment by MartinPotier** [comment] 2017-12-08 07:29
Had the same issue, that was fixed by running `stack2nix` in a nix-shell where ghc802 was available:
```
nix-shell -p haskell.compiler.ghc802
```
but of course you should have a `nix:` block in your `stack.yaml`.

**Comment by domenkozar** [comment] 2017-12-09 11:45
@MartinPotier @razvan-panda what git commit of stack2nix were you using?

**Comment by MartinPotier** [comment] 2017-12-09 14:16
https://github.com/input-output-hk/stack2nix/commit/fe3af222ae28a595aa943cd780470d09f5551e62 (used it on a private project, following haskell lts-8.5)

**Comment by domenkozar** [comment] 2017-12-24 14:43
I can finally reproduce this using isolated environment and a bunch of hacks using `haskell-ide-engine`:

```
$ nix-shell --pure -p glibcLocales nix git cabal-install cabal2nix --run "LANG=en_US.utf8 NIX_REMOTE=daemon NIX_PATH=nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs:nixos-config=/etc/nixos/configuration.nix:/nix/var/nix/profiles/per-user/root/channels stack2nix . > pkgs.nix"
```

Looking into what's going on.

**Comment by kirelagin** [comment] 2018-01-11 08:46
@domenkozar You said you figured out what the cause of the issue was, woul you be able to quickly sum it up? Is that because stack the library does not leverage Nix integration?

I think that it is a reasonable assumption that `stack2nix` will be used on a host that has Nix installed and thus it should be possible to somehow extract the GHC version required by stack (I don’t think there is a way to do it now but it probably could be added to the `stack query` interface) and then reexec in a nix-shell with an appropriate version of GHC (and, if we are doing this anyway, `cabal-install`, `cabal2nix`, and `nix-prefetch-git` as well).

**Comment by kirelagin** [comment] 2018-01-11 08:48
However, if you don’t feel like adding this functionality to `stack2nix` itself, it can be simply documented, that one needs to have the right version of GHC available. In any case, it seems that this issue warrants a PR into stack to expose the required GHC version, so that users will be able to run `stack2nix` in a properly configured shell.

**Comment by domenkozar** [comment] 2018-01-11 17:11
Could you try https://github.com/input-output-hk/stack2nix/pull/83

**Closed** 2018-01-11 19:58 UTC
