### ISSUE TITLE
Failed calls to cabal2nix are silently ignored

### ISSUE THREAD

**Issue by domenkozar** [input-output-hk/stack2nix#15] opened 2017-06-07 13:41 UTC
If cabal2nix returns an error, error out stack2nix as well.

**Comment by cleverca22** [comment] 2017-07-08 00:10
i have identified 3 separate bugs that are involved in this problem

1. `mapConcurrent` in [1] drops all exceptions
2. `replaceSymlink` in [2] can collide with itself on the `.new_` variant of the path
3. `downloadCached` in [3] calls `replaceSymlink` even if the symlink doesn't need replacing

3 makes 2 happen more often (on every single eval of `<nixpkgs>` i think), then 1 causes `stack2nix` to ignore the failure caused by 2
[1] https://github.com/input-output-hk/stack2nix/blob/3f2d4d31b1936dda71ce9a3be145c6407685045e/src/Stack2nix.hs#L160-L164
[2] https://github.com/NixOS/nix/blob/177f3996e28967368791ba0e4ec036f3dbbb88d0/src/libutil/util.cc#L497-L505
[3] https://github.com/NixOS/nix/blob/c0015e87af70f539f24d2aa2bc224a9d8b84276b/src/libstore/download.cc#L665

**Comment by mckeankylej** [comment] 2017-07-08 00:32
```haskell
#!/usr/bin/env nix-shell
#! nix-shell -j 4 -i runhaskell -p 'pkgs.haskellPackages.ghcWithPackages (hp: with hp; [text transformers async SafeSemaphore])'
module Main where

import qualified Data.Text as T
import qualified Data.Text.IO as T
import Control.Monad (void,when)
import Control.Monad.Trans.Cont (ContT(..),runContT)
import Control.Concurrent (threadDelay)
import Control.Concurrent.Async (withAsync,wait)
import Control.Concurrent.MSem (new,with)

printSleep :: Int -> IO ()
printSleep x = do
  when (x == 666) (fail "hail satan")
  T.putStrLn (T.pack (show x))
  threadDelay 1000000

mapPool :: Traversable t => Int -> (a -> IO b) -> t a -> IO (t b)
mapPool cap f as = do
  sem <- new cap
  runContT
    (traverse (ContT . withAsync . with sem . f) as)
    (traverse wait)

main :: IO ()
main = void (mapPool 4 printSleep [1..1000])
```
Here is a start to a mapPool that respects exceptions

**Comment by domenkozar** [comment] 2017-07-10 15:47
2-3) https://github.com/NixOS/nix/issues/849#issue-140669755

**Comment by jmitchell** [comment] 2017-07-12 17:59
A fix for (1) is merged into master. In addition to exposing errors in concurrent cabal2nix runs there's a new `-j` option to specify the maximum number of threads. The default is 1 thread, so (2) and (3) should be mitigated. There's an [upstream fix](https://github.com/NixOS/nix/commit/2965d40612e16388ef2177d2a13d168848c6ca8a) for the race condition as well.

**Closed by jmitchell** 2017-07-12 17:59 UTC
Labels: bug
