### ISSUE TITLE
stack2nix hangs

### ISSUE THREAD

**Issue by arianvp** [input-output-hk/stack2nix#66] opened 2017-08-30 07:39 UTC
This is the output, then it just hangs:
```
╰─$ stack2nix .
Ensuring cabal2nix version is >= 2.2.1 ...
Ensuring git version is >= 2 ...
Ensuring cabal version is >= 1 ...
```

Versions:

```
╭─arian@channable-desktop  ~/channable/xx  ‹master*› 
╰─$ uname -a
Linux channable-desktop 4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
╭─arian@channable-desktop  ~/channable/xx  ‹master*› 
╰─$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
╭─arian@channable-desktop  ~/channable/xx  ‹master*› 
╰─$ cabal --version
cabal-install version 1.24.0.2
compiled using version 1.24.2.0 of the Cabal library 
╭─arian@channable-desktop  ~/channable/xx  ‹master*› 
╰─$ stack --version
Version 1.4.0, Git revision 5986498a9d1073e8d58c79ec1302bb2a7847a396 (4642 commits) x86_64 hpack-0.17.0
╭─arian@channable-desktop  ~/channable/xx  ‹master*› 
╰─$ cabal2nix --version
cabal2nix 2.4
╭─arian@channable-desktop  ~/channable/xx  ‹master*› 
╰─$ nix-env --version
nix-env (Nix) 1.11.13

```

**Comment by domenkozar** [comment] 2017-08-30 10:02
Are you using master branch of stack2nix?

**Comment by arianvp** [comment] 2017-08-30 14:12
Yes I am, i'll try to take a tagged release as well when I'm back at work :)

**Comment by jmitchell** [comment] 2017-08-30 14:50
I'm reproducing this on macOS. Looks like it hangs on `withBuildConfig` at https://github.com/input-output-hk/stack2nix/blob/334c903f0d3388f59195fc7e5af5333f998fe21e/src/Stack2nix/External/Stack.hs#L154.

**Comment by jesuspc** [comment] 2017-09-14 13:23
It reproduces in NixOs too.

**Comment by domenkozar** [comment] 2017-09-18 17:01
@jesuspc can you always reproduce or is it intermittent?

**Comment by domenkozar** [comment] 2017-09-20 15:56
This was a recent commit in master, we are still investigating. Feedback welcome - any ideas how to debug it.

**Comment by ip1981** [comment] 2017-09-21 11:33
For me it hangs while running 
`/nix/store/9dhgi9b6n66srwk9dx60sdanrjcmgbpr-ghc-8.2.1/lib/ghc-8.2.1/bin/ghc-pkg --global-package-db /nix/store/9dhgi9b6n66srwk9dx60sdanrjcmgbpr-ghc-8.2.1/lib/ghc-8.2.1/package.conf.d --global --no-user-package-db dump --expand-pkgroot`

This command itself is very quck.

**Comment by domenkozar** [comment] 2017-09-21 13:07
@ip1981 could you run `killall -SIGUSR2 stack2nix` to get the stack trace?

**Comment by ip1981** [comment] 2017-09-21 13:42
> This build does not support backtraces

I built it with `default.nix` from this repository :)

**Comment by domenkozar** [comment] 2017-09-21 14:10
@ip1981 it seems you're using ghc-8.2.1, that's confusing because if you ran `nix-build default.nix` you should be using ghc-8.0.2 as per https://github.com/input-output-hk/stack2nix/blob/master/stack2nix.nix#L6

**Comment by ip1981** [comment] 2017-09-21 14:16
In fact I used this code:

```
  nixpkgs =
    let
      boot = import <nixpkgs> {};
      source = boot.pkgs.fetchFromGitHub {
        owner = "NixOS";
        repo = "nixpkgs";
        rev = "ebc1127cb95f39d5f99f78b0e8bd7cf33861d467";
        sha256 = "12wpyccp6a7g28csqlgk3yi3yds33rpfsf6lvxys7j76wcxicglx";
      };
  in import source {};

  inherit (nixpkgs) pkgs;

  stack2nix =
    let
      source = pkgs.fetchFromGitHub {
        owner = "input-output-hk";
        repo = "stack2nix";
        rev = "ed710c37b126f9766002db72f23886f5e7023969";
        sha256 = "16lvbkbfh0yh3qdm304p2bydnp6pnxg2iksji3z7krwwwfx82iqf";
      };
    in import source { inherit pkgs; };

```

**Comment by razvan-panda** [comment] 2017-11-03 19:48
Also hanging on my machine.
To reproduce git clone https://github.com/haskell/haskell-ide-engine

    cp stack-8.2.1.yaml stack.yaml
    stack2nix . > default.nix:

```
[neo@nixos:~/Sources/haskell-ide-engine]$ stack2nix . > default.nix
Ensuring cabal2nix version is >= 2.2.1 ...
Ensuring git version is >= 2 ...
Ensuring cabal version is >= 1 ...
```

cabal2nix is failing to work because of this subdirs usage: https://github.com/haskell/haskell-ide-engine/blob/master/stack-8.2.1.yaml#L44-L45

**Comment by domenkozar** [comment] 2017-11-08 19:28
I can't reproduce this (NixOS):

```
$ /nix/store/fskgcffnbysdcrcykcs2zk192n6ggicr-stack2nix-0.1.3.0/bin/stack2nix . > foo.nix
Ensuring cabal2nix version is >= 2.2.1 ...
Ensuring git version is >= 2 ...
Ensuring cabal version is >= 1 ...
Cloning into '/home/ielectric/dev/haskell-ide-engine/.s2n/downloaded/HuZs3qJXFDmk'...
remote: Counting objects: 1415, done.
remote: Compressing objects: 100% (381/381), done.
remote: Total 1415 (delta 659), reused 1375 (delta 637)
```

**Comment by razvan-panda** [comment] 2017-11-08 19:33
@domenkozar did you run `cp stack-8.2.1.yaml stack.yaml` before running stack2nix ?

**Comment by domenkozar** [comment] 2017-11-08 19:45
@razvan-panda in that case I hit https://github.com/input-output-hk/stack2nix/issues/74

**Comment by domenkozar** [comment] 2017-11-08 19:50
@razvan-panda did you build stack2nix via stack or nix?

**Comment by razvan-panda** [comment] 2017-11-08 19:54
@domenkozar via stack
stack2nix is not packaged correctly under Nix

**Comment by razvan-panda** [comment] 2017-11-08 19:55
https://github.com/NixOS/nixpkgs/issues/30899

**Comment by domenkozar** [comment] 2017-11-08 20:04
@razvan-panda could you try using branch on https://github.com/input-output-hk/stack2nix/pull/73 and run `nix-build` on stack2nix repo? Then see if it still hangs.

**Comment by razvan-panda** [comment] 2017-11-08 20:53
@domenkozar built that branch using nix-build and it still hangs on it:

```
[neo@nixos:~/Sources/haskell-ide-engine]$ /nix/store/hp58vagzy514vn8r9hjnyc8x7kwrd669-stack2nix-0.1.3.0/bin/stack2nix . > default.nix
Ensuring cabal2nix version is >= 2.2.1 ...
Ensuring git version is >= 2 ...
Ensuring cabal version is >= 1 ...
```

1 CPU core gets maxed out for 10-15 seconds, then goes down to almost nothing and nothing happens.

**Comment by domenkozar** [comment] 2017-12-09 11:39
@razvan-panda could I ask you to retry with the branch in https://github.com/input-output-hk/stack2nix/pull/75 - we've done a bunch of refactoring in last month.

**Comment by domenkozar** [comment] 2017-12-13 11:27
Maybe @ip1981, @jesuspc or @arianvp can help restest as well:

```
git pull
git checkout ksaric/DEVOPS-464
nix-build
./result/bin/stack2nix folder/
```

**Comment by jesuspc** [comment] 2017-12-18 09:43
@domenkozar I just retested with the ksaric/DEVOPS-464 branch on the pandoc repo and it worked fine. Thanks!

**Comment by domenkozar** [comment] 2017-12-18 09:59
@jesuspc note that there is a bug with missing deps, we're looking into that. Otherwise it's almost ready :)

**Comment by domenkozar** [comment] 2017-12-18 10:09
@razvan-panda @ip1981 can you guys confirm? Thanks!

**Comment by arianvp** [comment] 2017-12-18 10:48
Building as we speak.. will report soon

**Comment by arianvp** [comment] 2017-12-18 11:07
It works now!

**Comment by arianvp** [comment] 2017-12-18 11:08
However, the generated `default.nix` doesn't actually work:

```
╰─$ nix-build
error: attribute ‘applicative-quoters’ missing, at /nix/store/inyp9ffpwkqcp0z94cr3a1wi6shrxcas-nixpkgs-18.03pre122585.b212125b541/nixpkgs/pkgs/development/haskell-modules/configuration-ghc-8.0.x.nix:42:37

```

**Comment by domenkozar** [comment] 2017-12-18 11:11
Great! :) @arianvp you can't build the whole package set yet (we have a fix WIP), but you can try using `nix-build -A <package>`

**Comment by domenkozar** [comment] 2017-12-22 17:32
This was fixed in master.

**Closed by domenkozar** 2017-12-22 17:32 UTC
